resources:
- name: src
  type: git
  source:
    uri: git@github.com:hpcloud/hcf-configgin.git
    branch: develop
    private_key: {{git-private-key}}
- name: src-ci
  type: git
  source:
    uri: git@github.com:hpcloud/hcf-configgin-ci.git
    branch: develop
    private_key: {{git-private-key}}
- name: s3.hcf-ci-concourse-configgin
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: configgin-(.*).tgz
    private: true
jobs:
- name: lint
  plan:
  - aggregate:
    - get: src-ci
      trigger: true
    - get: src
      trigger: true
  - task: lint
    file: src-ci/tasks/lint.yaml
- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: test
    file: src-ci/tasks/test.yaml
- name: dist
  plan:
  - aggregate:
    - get: src
      passed: [lint, test]
      trigger: true
    - get: src-ci
      passed: [lint, test]
      trigger: true
  - task: dist
    file: src-ci/tasks/dist.yaml
  - put: s3.hcf-ci-concourse-configgin
    params:
      file: dist/configgin-(.*).tgz
      acl: public-read
