resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: helioncf/concourse-github-pull-request
- name: status
  type: docker-image
  source:
    repository: helioncf/concourse-github-status
resources:
- name: src
  type: pull-request
  source:
    uri: git@github.com:hpcloud/hcf-configgin.git
    branch: develop
    access_token: {{github-access-token}}
    private_key: {{git-private-key}}
- name: src-ci
  type: git
  source:
    uri: git@github.com:hpcloud/hcf-configgin-ci.git
    branch: develop
    private_key: {{git-private-key}}
- name: status
  type: status
  source:
    repo: hpcloud/configgin
    access_token: {{github-access-token}}
- name: s3.hcf-ci-concourse-configgin
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: 'configgin-(.*)\.tgz'
    private: true
jobs:
- name: lint
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      path: src
      context: lint
      state: pending
      description: make lint
  - task: lint
    file: src-ci/tasks/lint.yaml
    on_success:
      put: status
      params:
        path: src
        context: lint
        state: success
        description: make lint
    on_failure:
      put: status
      params:
        path: src
        context: lint
        state: failure
        description: make lint
- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      path: src
      context: test
      state: pending
      description: make test
  - task: test
    file: src-ci/tasks/test.yaml
    on_success:
      put: status
      params:
        path: src
        context: test
        state: success
        description: make test
    on_failure:
      put: status
      params:
        path: src
        context: test
        state: failure
        description: make test
- name: dist
  plan:
  - aggregate:
    # Don't use the passed: attribute from the normal pipeline, there is no true
    # dependency as well as we want all the statuses to be set in parallel.
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      path: src
      context: dist
      state: pending
      description: packaging
  - task: dist
    file: src-ci/tasks/dist.yaml
    on_success:
      put: status
      params:
        path: src
        context: dist
        state: success
        description: packaging
    on_failure:
      put: status
      params:
        path: src
        context: dist
        state: failure
        description: packaging
  - put: s3.hcf-ci-concourse-configgin
    params:
      from: 'dist/configgin-(.*)\.tgz'
