resources:
- name: src
  type: git
  source:
    uri: https://github.com/SUSE/configgin.git
    branch: master

- name: ci
  type: git
  source:
    uri: https://github.com/SUSE/configgin-ci.git
    branch: master

- name: out
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}
    endpoint: {{s3-endpoint}}
    bucket: configgin
    regexp: configgin-(.*).tgz
    private: true

jobs:
- name: lint
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: src
      trigger: true
  - task: lint
    file: ci/tasks/lint.yml

- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
      trigger: true
  - task: test
    file: ci/tasks/test.yml

- name: dist
  plan:
  - aggregate:
    - get: src
      passed: [lint, test]
      trigger: true
    - get: ci
      passed: [lint, test]
      trigger: true
  - task: dist
    file: ci/tasks/dist.yml
  - put: out
    params:
      file: out/configgin-*.tgz
      acl: public-read
