resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
resources:
- name: src
  type: pull-request
  source:
    uri: git@github.com:hpcloud/hcf-configgin.git
    branch: develop
    access_token: {{github-access-token}}
    private_key: {{git-private-key}}
- name: src-ci
  type: git
  source:
    uri: git@github.com:hpcloud/hcf-configgin-ci.git
    branch: develop
    private_key: {{git-private-key}}
- name: s3.hcf-ci-concourse-configgin
  type: s3
  source:
    region_name: us-west-2
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-hpe
    regexp: 'configgin-(.*)\.tgz'
    private: true
jobs:
- name: lint
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: set-status-pending
    file: src-ci/tasks/status.yaml
    config:
      run:
        path: src-ci/scripts/set-status.sh
        args: [lint, pending, 'make lint']
      params:
        GITHUB_ACCESS_TOKEN: {{github-access-token}}
  - task: lint
    file: src-ci/tasks/lint.yaml
    on_success:
      task: set-status-success
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [lint, success, 'make lint']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
    on_failure:
      task: set-status-failed
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [lint, failure, 'make lint']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: set-status-pending
    file: src-ci/tasks/status.yaml
    config:
      run:
        path: src-ci/scripts/set-status.sh
        args: [test, pending, 'make test']
      params:
        GITHUB_ACCESS_TOKEN: {{github-access-token}}
  - task: test
    file: src-ci/tasks/test.yaml
    on_success:
      task: set-status-success
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [test, success, 'make test']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
    on_failure:
      task: set-status-failed
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [test, failure, 'make test']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
- name: dist
  plan:
  - aggregate:
    # Don't use the passed: attribute from the normal pipeline, there is no true
    # dependency as well as we want all the statuses to be set in parallel.
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - task: set-status-pending
    file: src-ci/tasks/status.yaml
    config:
      run:
        path: src-ci/scripts/set-status.sh
        args: [dist, pending, 'packaging']
      params:
        GITHUB_ACCESS_TOKEN: {{github-access-token}}
  - task: dist
    file: src-ci/tasks/dist.yaml
    on_success:
      task: set-status-success
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [dist, success, 'packaging']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
    on_failure:
      task: set-status-failed
      file: src-ci/tasks/status.yaml
      config:
        run:
          path: src-ci/scripts/set-status.sh
          args: [dist, failure, 'packaging']
        params:
          GITHUB_ACCESS_TOKEN: {{github-access-token}}
  - put: s3.hcf-ci-concourse-configgin
    params:
      from: 'dist/configgin-(.*)\.tgz'
