resources:
- name: src
  type: pull-request
  source:
    access_token: {{github-access-token}}
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:hpcloud/configgin.git
- name: src-ci
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:hpcloud/configgin-ci.git
- name: status
  type: status
  source:
    access_token: {{github-access-token}}
    repo: hpcloud/configgin
- name: s3.hcf-ci-concourse-configgin
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: concourse-hpe
    private: true
    regexp: configgin-(.*)\.tgz
    region_name: us-west-2
    secret_access_key: {{aws-secret-access-key}}
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: heliondevops/concourse-github-pull-request
- name: status
  type: docker-image
  source:
    repository: heliondevops/concourse-github-status
jobs:
- name: lint
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      context: lint
      description: make lint
      path: src
      state: pending
  - task: lint
    file: src-ci/tasks/lint.yaml
    on_failure:
      put: status
      params:
        context: lint
        description: make lint
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: lint
        description: make lint
        path: src
        state: success
- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      context: test
      description: make test
      path: src
      state: pending
  - task: test
    file: src-ci/tasks/test.yaml
    on_failure:
      put: status
      params:
        context: test
        description: make test
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: test
        description: make test
        path: src
        state: success
- name: dist
  plan:
  - aggregate:
    # Don't use the passed: attribute from the normal pipeline, there is no true
    # dependency as well as we want all the statuses to be set in parallel.
    - get: src
      trigger: true
    - get: src-ci
      trigger: true
  - put: status
    params:
      context: dist
      description: packaging
      path: src
      state: pending
  - task: dist
    file: src-ci/tasks/dist.yaml
    on_failure:
      put: status
      params:
        context: dist
        description: packaging
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: dist
        description: packaging
        path: src
        state: success
  - put: s3.hcf-ci-concourse-configgin
    params:
      from: dist/configgin-(.*)\.tgz
