resources:
- name: src
  type: git
  source:
    uri: git@github.com:hpcloud/configgin.git
    branch: master

- name: ci
  type: git
  source:
    uri: git@github.com:hpcloud/configgin-ci.git
    branch: jandubois-ci-from-the-cloud

- name: out
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret-key}}
    bucket: configgin
    regexp: configgin-(.*).tgz
    private: true

jobs:
- name: lint
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: src
      trigger: true
  - task: lint
    file: ci/tasks/lint.yaml

- name: test
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
      trigger: true
  - task: test
    file: ci/tasks/test.yaml

- name: dist
  plan:
  - aggregate:
    - get: src
      passed: [lint, test]
      trigger: true
    - get: ci
      passed: [lint, test]
      trigger: true
  - task: dist
    file: ci/tasks/dist.yaml
  - put: out
    params:
      file: dist/configgin-*.tgz
      acl: public-read
