---
resources:
- name: src
  type: pull-request
  source:
    access_token: {{github-access-token}}
    uri: git@github.com:SUSE/configgin.git
    base: master
    private_key: {{github-private-key}}
    disable_forks: true

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/SUSE/configgin-ci.git

- name: status
  type: status
  source:
    access_token: {{github-access-token}}
    repo: SUSE/configgin

- name: s3.configgin
  type: s3
  source:
    access_key_id: {{aws-access-key}}
    bucket: configgin
    regexp: checks/configgin-(.*)\.gem
    secret_access_key: {{aws-secret-key}}
    private: true

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: status
  type: docker-image
  source:
    repository: splatform/concourse-github-status

jobs:
- name: lint
  plan:
  - aggregate:
    - get: src
      version: every
      trigger: true
    - get: ci
      trigger: true
  - put: status
    params:
      context: lint
      description: make lint
      path: src
      state: pending
  - task: lint
    file: ci/tasks/lint.yml
    on_failure:
      put: status
      params:
        context: lint
        description: make lint
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: lint
        description: make lint
        path: src
        state: success

- name: test
  plan:
  - aggregate:
    - get: src
      version: every
      trigger: true
    - get: ci
      trigger: true
  - put: status
    params:
      context: test
      description: make test
      path: src
      state: pending
  - task: test
    file: ci/tasks/test.yml
    on_failure:
      put: status
      params:
        context: test
        description: make test
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: test
        description: make test
        path: src
        state: success

- name: dist
  plan:
  - aggregate:
    # Don't use the passed: attribute from the normal pipeline, there is no true
    # dependency as well as we want all the statuses to be set in parallel.
    - get: src
      version: every
      trigger: true
    - get: ci
      trigger: true
  - put: status
    params:
      context: dist
      description: packaging
      path: src
      state: pending
  - task: dist
    file: ci/tasks/dist.yml
    on_failure:
      put: status
      params:
        context: dist
        description: packaging
        path: src
        state: failure
    on_success:
      put: status
      params:
        context: dist
        description: packaging
        path: src
        state: success
  - put: s3.configgin
    params:
      file: s3.configgin/configgin-*.gem
      acl: public-read
