---
platform: linux
image_resource:
 type: docker-image
 source:
  repository: ruby
  tag: '2.1.5'

inputs:
  - name: src

outputs:
  - name: dist

run:
  path: sh
  args:
    - -c
    - make -C src dist && mv src/output/* dist/
