---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.1.5'

inputs:
- name: src

outputs:
- name: out

run:
  path: make
  args: [ -C src dist && mv src/output/* out/ ]
